export const technicalStatNames = [
  "corners",
  "crossing",
  "dribbling",
  "finishing",
  "first_touch",
  "free_kick_taking",
  "heading",
  "long_shots",
  "long_throws",
  "marking",
  "passing",
  "penalty_taking",
  "tackling",
  "technique",
];

export const mentalStatNames = [
  "aggression",
  "anticipation",
  "bravery",
  "composure",
  "concentration",
  "decisions",
  "determination",
  "flair",
  "leadership",
  "off_the_ball",
  "positioning",
  "teamwork",
  "vision",
  "work_rate",
];

export const physicalStatNames = [
  "acceleration",
  "agility",
  "balance",
  "jumping_reach",
  "natural_fitness",
  "pace",
  "stamina",
  "strength",
];

export const goalkeeperStatNames = [
  "aerial_reach",
  "command_of_area",
  "communication",
  "eccentricity",
  "first_touch",
  "handling",
  "kicking",
  "one_on_ones",
  "passing",
  "punching",
  "reflexes",
  "rushing_out",
  "throwing",
];
